reserved-nicknames:
  nicknames:
    - admin
    - administrator
    - system
    - root
    - 운영자
    - 관리자
    - moderator
    - 운영팀
    - nadab
    - ifive
    - devkor
    - master
    - guest
    - 테스트
    - test
    - 마스터
    - 매니저
    - 시스템
    - 어드민