CREATE TABLE ask_chat_sample_questions (
    id            BIGSERIAL    PRIMARY KEY,
    interest_code VARCHAR(50)  NOT NULL,
    question      VARCHAR(200) NOT NULL,
    display_order INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_ask_chat_sample_questions_interest_code
        FOREIGN KEY (interest_code) REFERENCES interests(code)
);

CREATE INDEX idx_ask_chat_sample_questions_active_interest_order
    ON ask_chat_sample_questions(active, interest_code, display_order);

INSERT INTO ask_chat_sample_questions (id, interest_code, question, display_order, active) VALUES
    (1, 'PREFERENCE', '나 진짜 뭘 좋아하는 사람이야?', 1, TRUE),
    (2, 'PREFERENCE', '내가 모르는 내 취향이 있어?', 2, TRUE),
    (3, 'PREFERENCE', '내가 반복해서 돌아가는 게 있어?', 3, TRUE),
    (4, 'PREFERENCE', '나 요즘 뭘 보고 위로받아?', 4, TRUE),
    (5, 'PREFERENCE', '나한테 안 맞는데 억지로 맞추는 취향이 있어?', 5, TRUE),
    (6, 'PREFERENCE', '내가 피곤할 때 찾는게 뭐야?', 6, TRUE),
    (7, 'PREFERENCE', '내가 꾸준히 좋아하는 게 뭐야?', 7, TRUE),
    (8, 'PREFERENCE', '나 요즘 새로 빠진 게 있어?', 8, TRUE),
    (9, 'PREFERENCE', '남들은 좋아하는데 나만 싫어하는 게 있어?', 9, TRUE),
    (10, 'PREFERENCE', '내가 스트레스 받을 때 하는 행동은 뭐가 있어?', 10, TRUE),
    (11, 'PREFERENCE', '내 취향들의 공통점은 뭐야?', 11, TRUE),
    (12, 'EMOTION', '내가 가장 많이 억누르는 감정은 뭐야?', 12, TRUE),
    (13, 'EMOTION', '내가 자꾸 피하는 감정이 뭐야?', 13, TRUE),
    (14, 'EMOTION', '내가 가장 행복할 땐 언제일까?', 14, TRUE),
    (15, 'EMOTION', '내가 감정 표현을 잘 못하는 상황이 언제야?', 15, TRUE),
    (16, 'EMOTION', '요즘 나를 가장 지치게 만드는 게 뭐야?', 16, TRUE),
    (17, 'EMOTION', '내가 언제 가장 무너지는 것 같아?', 17, TRUE),
    (18, 'EMOTION', '내가 화나는 모먼트는 뭘까?', 18, TRUE),
    (19, 'EMOTION', '내가 가장 약해지는 감정은 뭘까?', 19, TRUE),
    (20, 'EMOTION', '내 감정기복은 심한 편이야?', 20, TRUE),
    (21, 'EMOTION', '내가 가장 자주 느끼는 감정이 궁금해.', 21, TRUE),
    (22, 'EMOTION', '내가 후회하고 있는 게 있어?', 22, TRUE),
    (23, 'EMOTION', '나는 감정을 숨기는 편이야?', 23, TRUE),
    (24, 'EMOTION', '내 감정의 매커니즘은 뭘까?', 24, TRUE),
    (25, 'EMOTION', '나의 치명적인 결핍이 뭔 것 같아?', 25, TRUE),
    (26, 'ROUTINE', '내 하루에서 제일 낭비되는 시간이 언제야?', 26, TRUE),
    (27, 'ROUTINE', '내가 무너지기 직전에 나오는 신호가 뭐야?', 27, TRUE),
    (28, 'ROUTINE', '내가 지속적으로 미루는 건 뭐야?', 28, TRUE),
    (29, 'ROUTINE', '나의 생산적인 시간대가 언제야?', 29, TRUE),
    (30, 'ROUTINE', '나에게 좋은 휴식 방법은 뭐가 있을까?', 30, TRUE),
    (31, 'ROUTINE', '나는 언제 가장 집중을 잘할까?', 31, TRUE),
    (32, 'RELATIONSHIP', '나한테 가장 큰 영향 준 사람이 누구야?', 32, TRUE),
    (33, 'RELATIONSHIP', '내 관계에서 반복되는 패턴은 뭐가 있어?', 33, TRUE),
    (34, 'RELATIONSHIP', '어떤 사람들한테 에너지를 뺏길까?', 34, TRUE),
    (35, 'RELATIONSHIP', '사람들이 나를 어떤 사람으로 볼 것 같아?', 35, TRUE),
    (36, 'RELATIONSHIP', '내가 첫인상으로 주는 느낌이 뭐야?', 36, TRUE),
    (37, 'RELATIONSHIP', '내가 의도치 않게 주는 인상이 있어?', 37, TRUE),
    (38, 'RELATIONSHIP', '사람들이 나한테 자주 하는 말이 있어?', 38, TRUE),
    (39, 'RELATIONSHIP', '내가 생각하는 나랑 남이 보는 나의 차이점은 뭐야?', 39, TRUE),
    (40, 'LOVE', '내가 좋아하는 사람은 어떤 사람이야?', 40, TRUE),
    (41, 'LOVE', '내가 좋아하면 어떤 행동이 나와?', 41, TRUE),
    (42, 'LOVE', '나는 연애하면 어떤 사람이 돼?', 42, TRUE),
    (43, 'LOVE', '내가 연애에서 반복하는 실수가 있어?', 43, TRUE),
    (44, 'LOVE', '나는 어떻게 표현하는 사람이야?', 44, TRUE),
    (45, 'VALUES', '내가 가장 두려워하는 게 뭐야?', 45, TRUE),
    (46, 'VALUES', '나는 10년 후에 어떤 모습일 것 같아?', 46, TRUE),
    (47, 'VALUES', '내 가치관 중 자꾸 흔들리는게 있어?', 47, TRUE),
    (48, 'VALUES', '너가 생각하는 난 어떤 사람이야?', 48, TRUE),
    (49, 'VALUES', '내가 지금 가장 후회하는 선택이 뭐야?', 49, TRUE),
    (50, 'VALUES', '나만의 행복이 뭐라고 생각해?', 50, TRUE),
    (51, 'VALUES', '내가 진짜 원하는 걸 포기하게 만드는 게 뭐야?', 51, TRUE),
    (52, 'VALUES', '내가 반복해서 넘지 못하는 벽이 있어?', 52, TRUE),
    (53, 'VALUES', '어떤 순간에 가장 성장한 것 같아?', 53, TRUE),
    (54, 'VALUES', '지금의 나를 만든 결정적인 선택이 뭔 것 같아?', 54, TRUE),
    (55, 'VALUES', '내가 3년 뒤에 실패한다면 지금의 무엇 때문일 것 같아?', 55, TRUE),
    (56, 'VALUES', '내 삶의 관점을 한 문장으로 요약하면?', 56, TRUE),
    (57, 'VALUES', '내가 피하는 주제는 뭐가 있어?', 57, TRUE);

SELECT setval('ask_chat_sample_questions_id_seq', (SELECT MAX(id) FROM ask_chat_sample_questions));
