package com.devkor.ifive.nadab.domain.wallet.core.entity;

public enum CrystalLogReason {
    DAILY_ANSWER_REWARD,

    REPORT_GENERATE_WEEKLY,
    REPORT_GENERATE_MONTHLY,
    REPORT_GENERATE_TYPE,
    REPORT_GENERATE_TYPE_FREE_FIRST,

    TEST_DELETE_REPORT_REFUND_WEEKLY,
    TEST_DELETE_REPORT_REFUND_MONTHLY,
    TEST_DELETE_REPORT_REFUND_TYPE,

    ADMIN_ADJUST
}
