package com.devkor.ifive.nadab.domain.wallet.core.entity;

public enum CrystalLogReason {
    DAILY_ANSWER_REWARD,

    REPORT_GENERATE_WEEKLY,
    REPORT_GENERATE_MONTHLY,
    REPORT_GENERATE_YEARLY,
    REPORT_GENERATE_ALL,

    TEST_DELETE_REPORT_REFUND_WEEKLY,
    TEST_DELETE_REPORT_REFUND_MONTHLY,

    ADMIN_ADJUST
}
